In [34]:
import numpy as no
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier
from tqdm import tqdm
import warnings
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.linear_model import *
from sklearn.ensemble import *
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
# Ignore all warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import (
    LogisticRegression,
    RidgeClassifier,
    SGDClassifier,
    PassiveAggressiveClassifier,
    Perceptron,
)
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.neighbors import (
    KNeighborsClassifier,
    RadiusNeighborsClassifier,
    NearestCentroid,
)
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    BaggingClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier,
    HistGradientBoostingClassifier,
    VotingClassifier,
)
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.discriminant_analysis import (
    LinearDiscriminantAnalysis,
    QuadraticDiscriminantAnalysis,
)
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import *
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder

import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier,
    BaggingClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
)
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
import warnings
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from tabulate import tabulate  # Import the tabulate library
from sklearn.neural_network import MLPClassifier


In [29]:

cloth = pd.read_json(
    '/content/modcloth_final_data.json',
    lines = True

)

cloth.head(5)

SyntaxError: incomplete input (<ipython-input-29-820911ee2920>, line 6)

In [45]:
cloth['quality'].unique()

array([ 5.,  3.,  2.,  1.,  4., nan])

In [4]:
cloth.shape

(82790, 18)

In [5]:
cloth.isnull().sum()

item_id               0
waist             79908
size                  0
quality              68
cup size           6255
hips              26726
bra size           6018
category              0
bust              70936
height             1107
user_name             0
length               35
fit                   0
user_id               0
shoe size         54875
shoe width        64183
review_summary     6725
review_text        6725
dtype: int64

In [6]:
cloth.drop(
    ['item_id','waist'],
    axis =1,
    inplace = True
)

In [7]:
cloth

size  quality cup size  hips  bra size   category bust   height  \
0         7      5.0        d  38.0      34.0        new   36  5ft 6in   
1        13      3.0        b  30.0      36.0        new  NaN  5ft 2in   
2         7      2.0        b   NaN      32.0        new  NaN  5ft 7in   
3        21      5.0     dd/e   NaN       NaN        new  NaN      NaN   
4        18      5.0        b   NaN      36.0        new  NaN  5ft 2in   
...     ...      ...      ...   ...       ...        ...  ...      ...   
82785     8      4.0        b   NaN      36.0  outerwear  NaN  5ft 8in   
82786    12      5.0    ddd/f   NaN      34.0  outerwear  NaN  5ft 5in   
82787    12      5.0   dddd/g  36.0      32.0  outerwear  NaN  5ft 4in   
82788    12      4.0      NaN   NaN       NaN  outerwear  NaN  5ft 3in   
82789     4      4.0        d  39.0      32.0  outerwear  NaN      6ft   

              user_name         length    fit  user_id  shoe size shoe width  \
0                 Emily     just right  small   991571        NaN        NaN   
1      sydneybraden2001     just right  small   587883        NaN        NaN   
2                 Ugggh  slightly long  small   395665        9.0        NaN   
3          alexmeyer626     just right    fit   875643        NaN        NaN   
4            dberrones1  slightly long  small   944840        NaN        NaN   
...                 ...            ...    ...      ...        ...        ...   
82785          Jennifer     just right    fit   727820        8.5    average   
82786             Kelli  slightly long  small   197040        NaN        NaN   
82787          elacount     just right    fit   102493        NaN        NaN   
82788      jennaklinner     just right    fit   756491        NaN        NaN   
82789   maireadsteadman     just right    fit    78305        NaN        NaN   

                  review_summary  \
0                            NaN   
1                            NaN   
2                            NaN   
3                            NaN   
4                            NaN   
...                          ...   
82785               Cute jacket!   
82786   It's a beautiful jacket.   
82787  I love this blazer. It is   
82788  I love this blazer!! I wo   
82789  I love this piece. I'm re   

                                             review_text  
0                                                    NaN  
1                                                    NaN  
2                                                    NaN  
3                                                    NaN  
4                                                    NaN  
...                                                  ...  
82785                                       Cute jacket!  
82786  It's a beautiful jacket. I love how it's knit ...  
82787  I love this blazer. It is a great office piece...  
82788  I love this blazer!! I wore it yesterday and g...  
82789       I love this piece. I'm really happy with it!  

[82790 rows x 16 columns]

In [9]:
cloth.drop(
    ['user_name', 'user_id', 'review_summary', 'review_text'],
    axis = 1,
    inplace = True
)


In [10]:
cloth.head(2)

size  quality cup size  hips  bra size category bust   height      length  \
0     7      5.0        d  38.0      34.0      new   36  5ft 6in  just right   
1    13      3.0        b  30.0      36.0      new  NaN  5ft 2in  just right   

     fit  shoe size shoe width  
0  small        NaN        NaN  
1  small        NaN        NaN

In [11]:
new_cloth = cloth.dropna(
    how = 'any'
)

In [12]:
new_cloth.head(2)

size  quality cup size  hips  bra size category bust   height      length  \
23     5      5.0        c  32.0      34.0      new   34  5ft 1in  just right   
40    18      5.0    ddd/f  44.0      38.0      new   43  5ft 4in  just right   

      fit  shoe size shoe width  
23  small        7.0    average  
40  small        8.5    average

In [13]:
new_cloth.shape

(7000, 12)

In [17]:
new_cloth['cup size'].value_counts()

cup size
c         1670
d         1419
b         1325
dd/e      1031
ddd/f      612
a          453
dddd/g     263
h           89
k           40
j           35
aa          34
i           29
Name: count, dtype: int64

In [18]:
clothes_copy = new_cloth.copy(

)

In [19]:
new_cloth

size  quality cup size  hips  bra size   category bust    height  \
23        5      5.0        c  32.0      34.0        new   34   5ft 1in   
40       18      5.0    ddd/f  44.0      38.0        new   43   5ft 4in   
49       11      5.0        c  37.0      36.0        new   35   5ft 2in   
65        9      5.0        c  42.0      38.0        new   38   5ft 2in   
100      20      3.0        c  45.0      40.0        new   38   5ft 7in   
...     ...      ...      ...   ...       ...        ...  ...       ...   
82714    20      4.0     dd/e  48.0      38.0  outerwear   43   5ft 1in   
82720    26      5.0        c  50.0      38.0  outerwear   43       6ft   
82751     8      3.0        d  34.0      34.0  outerwear   36   5ft 6in   
82753     4      3.0     dd/e  35.0      32.0  outerwear   36   5ft 6in   
82754    12      5.0     dd/e  39.0      36.0  outerwear   36  5ft 10in   

               length    fit  shoe size shoe width  
23         just right  small        7.0    average  
40         just right  small        8.5    average  
49      slightly long  small        6.0    average  
65     slightly short    fit        7.0    average  
100        just right    fit       10.0    average  
...               ...    ...        ...        ...  
82714   slightly long  large        8.5       wide  
82720      just right  small       10.5       wide  
82751      just right  small        6.5    average  
82753      just right    fit       10.5       wide  
82754  slightly short    fit        9.5    average  

[7000 rows x 12 columns]

In [20]:
plt.figure(
    figsize=(10,10)
)

sns.heatmap(
    clothes_copy.corr(),
    annot = True,

)

ValueError: could not convert string to float: 'c'

<Figure size 1000x1000 with 0 Axes>

In [22]:
y = new_cloth['quality']
X = new_cloth.drop(
   [ 'quality','height', 'hips', 'bust'],
    axis = 1
)

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)


In [24]:
Xtrain.shape

(5600, 8)

In [25]:


num_features = Xtrain.select_dtypes(exclude = "object")
cat_features = Xtrain.select_dtypes(include = "object")

In [26]:
num_features, cat_features

(       size  bra size  shoe size
 13386     8      38.0        8.0
 75638     9      34.0        6.5
 49034    12      34.0        8.5
 34613    15      36.0        8.5
 81979    12      34.0        7.5
 ...     ...       ...        ...
 47824     4      34.0        8.0
 63426    26      42.0       10.0
 63775    12      36.0        8.5
 65243     8      34.0        7.5
 11031    15      40.0        8.5
 
 [5600 rows x 3 columns],
       cup size   category         length    fit shoe width
 13386        d    dresses     just right  small    average
 75638        b    bottoms      very long  large    average
 49034        b       tops     just right  large    average
 34613   dddd/g        new     just right    fit    average
 81979        c  outerwear     just right    fit    average
 ...        ...        ...            ...    ...        ...
 47824        a       tops     just right  large    average
 63426        d    bottoms  slightly long    fit    average
 63775        d    botto

In [32]:
step1 = ColumnTransformer(
    transformers=[
        ('col_tnf', OneHotEncoder( drop='first', handle_unknown='ignore'),cat_features.columns),
        ('num_tnf', StandardScaler(),num_features.columns )
    ],
    remainder='passthrough'
)

In [33]:
step1


ColumnTransformer(remainder='passthrough',
                  transformers=[('col_tnf',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore'),
                                 Index(['cup size', 'category', 'length', 'fit', 'shoe width'], dtype='object')),
                                ('num_tnf', StandardScaler(),
                                 Index(['size', 'bra size', 'shoe size'], dtype='object'))])

In [37]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression, SGDClassifier, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from tabulate import tabulate
from tqdm import tqdm

# Function to evaluate the model
def evaluate_model(model, x_train, y_train, x_test, y_test):
    # Convert sparse data to dense if necessary
    if hasattr(x_train, 'toarray'):
        x_train = x_train.toarray()
    if hasattr(x_test, 'toarray'):
        x_test = x_test.toarray()

    pipe = Pipeline([
        ('Transform', step1),  # You need to define the 'step1' transformer
        ('model', model),
    ])

    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)

    # Use appropriate classification metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="macro")
    recall = recall_score(y_test, y_pred, average="macro")
    f1 = f1_score(y_test, y_pred, average="macro")

    # Calculate the confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    return accuracy, precision, recall, f1, cm

# Initialize different classification models
models = {
    'Logistic Regression': LogisticRegression(),
    'Random Forest Classifier': RandomForestClassifier(),
    'Gradient Boosting Classifier': GradientBoostingClassifier(),
    'AdaBoost Classifier': AdaBoostClassifier(),
    'Bagging Classifier': BaggingClassifier(),
    'Extra Trees Classifier': ExtraTreesClassifier(),
    'Support Vector Classifier': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree Classifier': DecisionTreeClassifier(),
    # 'Naive Bayes': GaussianNB(),
    # 'HistGradientBoosting Classifier': HistGradientBoostingClassifier(),
    # 'SGD Classifier': SGDClassifier(),
    # 'Passive Aggressive Classifier': PassiveAggressiveClassifier(),
    # 'Ridge Classifier': RidgeClassifier(),
    # 'MLP Neural Network': MLPClassifier(hidden_layer_sizes=(10,), max_iter=100),
}

# Create a list to store the results
results = []

# Evaluate and print classification metrics for different models
for model_name, model in tqdm(models.items()):
    accuracy, precision, recall, f1, cm = evaluate_model(model, Xtrain, ytrain, Xtest, ytest)
    results.append([model_name, accuracy, precision, recall, f1, cm])

# Print the results in a tabular form
headers = ["Model", "Accuracy", "Precision", "Recall", "F1 Score", "Confusion Matrix"]
print(tabulate(results, headers, tablefmt="grid"))

# Find the model with the highest accuracy
max_accuracy_index = np.argmax([result[1] for result in results])
best_model_name = results[max_accuracy_index][0]
best_model_cm = results[max_accuracy_index][5]

print(f"\nThe model with the highest accuracy is: {best_model_name} (Accuracy: {results[max_accuracy_index][1]:.4f})")

# Print the confusion matrix for the best model
print("\nConfusion Matrix for the Best Model:")
print(best_model_cm)


100%|██████████| 9/9 [00:15<00:00,  1.68s/it]

+------------------------------+------------+-------------+----------+------------+-------------------------+
| Model                        |   Accuracy |   Precision |   Recall |   F1 Score | Confusion Matrix        |
+==============================+============+=============+==========+============+=========================+
| Logistic Regression          |   0.390714 |    0.22897  | 0.222956 |   0.197746 | [[  0   0   2   5   8]  |
|                              |            |             |          |            |  [  0   0   9  26  38]  |
|                              |            |             |          |            |  [  0   0  34 100 195]  |
|                              |            |             |          |            |  [  0   0  18 120 321]  |
|                              |            |             |          |            |  [  0   0  22 109 393]] |
+------------------------------+------------+-------------+----------+------------+-------------------------+
| Random F

In [51]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tabulate import tabulate
from tqdm import tqdm

# Function to encode categorical features (if any)
def encode_features(x):
    from sklearn.preprocessing import LabelEncoder
    encoder = LabelEncoder()
    x = np.array(x)  # Convert to NumPy array
    for i in range(x.shape[1]):
        if isinstance(x[0, i], str):  # If column contains strings
            x[:, i] = encoder.fit_transform(x[:, i])  # Encode as integers
    return x

# Function to evaluate the neural network model
def evaluate_nn_model(x_train, y_train, x_test, y_test):
    # Ensure data is a NumPy array (in case it is a Pandas DataFrame)
    if isinstance(x_train, pd.DataFrame):
        x_train = x_train.to_numpy()
    if isinstance(x_test, pd.DataFrame):
        x_test = x_test.to_numpy()

    # Encode the features if necessary (in case they contain strings)
    x_train = encode_features(x_train)
    x_test = encode_features(x_test)

    # Normalize the data
    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    # Encode the target labels if they are categorical (strings)
    label_encoder = LabelEncoder()
    y_train_encoded = label_encoder.fit_transform(y_train)
    y_test_encoded = label_encoder.transform(y_test)

    # Build the improved neural network model
    model = Sequential()
    model.add(Dense(256, input_dim=x_train_scaled.shape[1], activation='relu'))  # Increased neurons
    model.add(BatchNormalization())  # Added Batch Normalization
    model.add(Dropout(0.4))  # Increased dropout rate
    model.add(Dense(128, activation='relu'))  # Hidden layer 1
    model.add(BatchNormalization())  # Batch Normalization
    model.add(Dropout(0.4))  # Dropout layer
    model.add(Dense(64, activation='relu'))  # Hidden layer 2
    model.add(Dense(5, activation='softmax'))  # Output layer (9 classes)

    # Compile the model with a learning rate scheduler
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    # Train the model
    model.fit(x_train_scaled, y_train_encoded, epochs=100, batch_size=64, verbose=1, validation_split=0.2)  # Increased epochs

    # Predict on the test set
    y_pred = np.argmax(model.predict(x_test_scaled), axis=1)

    # Use appropriate classification metrics
    accuracy = accuracy_score(y_test_encoded, y_pred)
    precision = precision_score(y_test_encoded, y_pred, average="macro", zero_division=0)
    recall = recall_score(y_test_encoded, y_pred, average="macro", zero_division=0)
    f1 = f1_score(y_test_encoded, y_pred, average="macro", zero_division=0)

    # Calculate the confusion matrix
    cm = confusion_matrix(y_test_encoded, y_pred)

    return accuracy, precision, recall, f1, cm

# Evaluate the improved neural network model
accuracy, precision, recall, f1, cm = evaluate_nn_model(Xtrain, ytrain, Xtest, ytest)

# Print the results
headers = ["Accuracy", "Precision", "Recall", "F1 Score", "Confusion Matrix"]
result = [
    [accuracy, precision, recall, f1, cm]
]

print(tabulate(result, headers, tablefmt="grid"))

# Print the confusion matrix
print("\nConfusion Matrix for the Neural Network:")
print(cm)


Epoch 1/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.3156 - loss: 1.7396 - val_accuracy: 0.4018 - val_loss: 1.3909
Epoch 2/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3696 - loss: 1.4254 - val_accuracy: 0.4062 - val_loss: 1.3192
Epoch 3/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3767 - loss: 1.3664 - val_accuracy: 0.3991 - val_loss: 1.2907
Epoch 4/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3986 - loss: 1.3189 - val_accuracy: 0.4277 - val_loss: 1.2890
Epoch 5/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3995 - loss: 1.2995 - val_accuracy: 0.4268 - val_loss: 1.2843
Epoch 6/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3873 - loss: 1.3135 - val_accuracy: 0.4036 - val_loss: 1.2894
Epoch 7/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3992 - loss: 1.2826 - val_accuracy: 0.4089 - val_loss: 1.2833
Epoch 8/100
70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4023 - loss: 1.2731 - val_accuracy: 0.4098 - 